
[build]
 base = "."
 publish = "client"
[dev]
publish = "client"



[dev.https]
    certFile = "cert.pem" # path to the certificate file
    keyFile = "privatekey.pem" # path to the private key file

[redirects.headers]
Access-Control-Allow-Origin="https://workflow-prod-799d4.firebaseapp.com"
[[redirects]]
from ="/api/fb-dev/*"
to="http://localhost:9000/:splat"
force = true
  status = 200


[[redirects]]
from ="/api/fb-prod/*"
to="https://workflow-prod-799d4.firebaseapp.com/:splat"



[functions]
  directory = "netlify/functions"