name: aggregate
on: [push]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS...
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: 'npm install'
      - name: Collector action step
        id: collector
        uses: ./.github/actions/collector-action
        with:
          page-url: 'https://www.defacto.com.tr/kadin-denim'
     # - name: Meta creator action step
      #  id: creator
       # uses: ./.github/actions/meta-creator-action
       # with:
       #   pageData: steps.collector.outputs.pageData
        #run: echo "The pageTitle is ${{steps.collector.outputs.pageData}}"

