name: aggregate
on: [push]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: Install dependencies
        run: 'npm install'
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-action
        with:
          who-to-greet: 'Serdar the Octocat'
      - name: Get the output time
        run: echo "The time was ${{steps.hello.outputs.time}}"

