name: aggregate
on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Project Name'
        required: true
      startedDateTime:
        description: 'startedDateTime'
        required: true
      fb_refresh_token:
        description: 'fb_refresh_token'
        required: true
      uid:
        description: 'uid'
        required: true
      api_key:
        description: 'api_key'
        required: true
      fb_database_url:
        description: 'fb_database_url'
        required: true
      email:
        description: 'email'
        required: true
jobs:
  aggregator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS...
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: 'npm install'
      - name: aggregation step
        id: collection
        run: projectName=${{github.event.inputs.projectName}} startedDateTime=${{github.event.inputs.startedDateTime}} fb_refresh_token="${{github.event.inputs.fb_refresh_token}}" uid="${{github.event.inputs.uid}}" api_key="${{github.event.inputs.api_key}}" fb_database_url="${{github.event.inputs.fb_database_url}}" email="${{github.event.inputs.email}}"  HEADLESS=true NEXT_TASK=page_collection ALL=TRUE  node page-collector/server.js
