name: aggregate
on: [push]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: echo 'hello aggregator'
      - uses: ./.github/actions/hello-action

